### ISSUE TITLE
Ile xP na skill pointa - tu zapisać wszyskie przemyślenia z tym związane

### ISSUE THREAD

**Issue by Shinigami072** [SuperEpicNothing/str#11]

**Comment by lukaszlamza** [comment]
Ja to widzę tak:
w sumie jest 60 skill pointów (6 skilli po 10 pt max)
- 12 dajemy na starcie (wszystkie skille mają po 2 punkty na start)
- 3 punkty dajemy na starcie do rozdania - i to mi się podoba i tak może zostać

zostaje więc 45 punktów do zdobycia

Proponuję:
- każdy level up sprawia, że dostaje się 5 punktów do rozdania (a więc maksymalnie może zajść 9 razy)
- bieżąca liczba Punktów Doświadczenia obliczana jest następująco:
- 1 punkt za każdy otwarty rozdział (ew. za każdy posiadany Argument, co wychodzi PRAWIE na to samo) --> razem 12
- 1 punkt za każdy posiadany Scroll --> razem 12 (?)
- 1 punkt za każdy posiadany Achievement --> razem 16 (?)
- 3 punkty za każdą wygraną walkę z Konfuzjuszem (może być ukryty item, wtedy całość PD-ów można by obliczyć na podstawie "karty postaci") -> razem 9

-.-.-.-.-.-.- WSZYSTKO Razem ok. 49, co oznacza, że
0-4 PD - poziom 0
5-9 PD - poziom 1
...
...
45-49 PD - poziom 9
Wejście na wyższy poziom oznacza jednorazowe przyznanie 5 nowych PDków do rozdania.

I tyle.

49 punktów oznacza, że teoretycznie ktoś, kto zdobędzie WSZYSTKO, będzie miał overflow, tj. będzie miał punkty do rozdania, ale wszystkie skille będą ma MAX, ale:
- ilość achievementów i scrolli jest w trybie OKOŁO, więc zostawmy sobie ten margines;
- nawet gdyby tak było, nie widzę przeszkód; zawsze byłem dumny, kiedy udało mi się w jakiejś grze osiągnąć max skill pointów i wciąż mieć punkty do rozdania; nie traktowałem tego nigdy jako wady produktu, tylko jako świadectwo tego, jak wspaniałym jestem graczem :-)

**Comment by Shinigami072** [comment]
zaimplementowałem wszystkie propozycje i mam następujące uwagi:
- pasek xp posiada 8 segmentów, najlepszy efekt graficzny uzyskamy z ilością XP będąca wielokrotnością 2, 
- W celu sprawdzania wygranych z konfuzjuszem dodałem tag ID do konfuzjusza, pozwala na unikniecie zaliczenia dalej wygranej 2 krotnie, musi być unikalny dla każdej walki.
- obecnie stosuje się do liczenia odblokowanych rozdziałów, ale posiada do wadę, mianowicie możemy "ignorować" 2 pierwsze "lekcje", lub posiadać postać która zaczyna z jakimś doświadczeniem.
- uważam, możliwość zdobycia większej ilości XP niż można wykorzystać za dobrą rzecz.
