### ISSUE TITLE
Inwentarz, karta postaci, inne drobiazgi tekstowe

### ISSUE THREAD

**Issue by lukaszlamza** [SuperEpicNothing/str#15]
- w karcie postaci: "Zdolności?" -> "Umiejętności"
- na stronie głównej: 
  Nowa gra
  Kontynuuj grę
  O co chodzi? / Pomoc (właśnie tak, tzn. z ukośnikiem "O co chodzi? / Pomoc")

**Comment by lukaszlamza** [comment]
Aha, widzę, że inwentarz jest już zrobiony...

**Comment by Shinigami072** [comment]
Zmieniono tekst, pozostawiam otwarte
