### ISSUE TITLE
konflikt oznaczeń w ASSETS - ważne!

### ISSUE THREAD

**Issue by lukaszlamza** [SuperEpicNothing/str#16]
Przy nazywaniu ikon ITEMÓW nie mogą pojawiać się nazwy zajęte już przez obrazki POSTACI. Przed chwilą w oknie dialogowym z Hawkingiem zamiast buźki Hawkinga wyskoczyła mi ikonka młota. :-) Dopisałem cyfrę 5 po każdej nazwie itemu, teraz młot odpowiadający Tornadu Czasoprzestrzennemu ma nazwę "hawking5", to samo z Popperem.

**Comment by Shinigami072** [comment]
nie dodał pan commita ze zmianą

**Comment by lukaszlamza** [comment]
już zrobione
