### ISSUE TITLE
ENHANCEMENT: wł/wył trybu nauczyciela przeładowuje stronę

### ISSUE THREAD

**Issue by lukaszlamza** [SuperEpicNothing/str#23]
Chodzi o to, że obecnie po wł/wył trybu nauczyciela nie ma zmian w inwentarzu, tj. np. po wyłączeniu trybu nauczyciela wciąż widać wszystkie księgi/argumenty. Odświeżenie strony rozwiązuje problem.

**Comment by Shinigami072** [comment]
fixed
