### ISSUE TITLE
uwaga - zmiana w ikonie argumentu

### ISSUE THREAD

**Issue by lukaszlamza** [SuperEpicNothing/str#24]
Zmieniłem ikonę argumentu "Demon Kartezjusza", żeby drugi argument bardziej się odróżniał. Ogólnie jestem teraz bardziej zadowolony z ikony Demona, ale gdyby to powodowało jakieś problemy z koncepcją animacji etc., daj znać, ponegocjujemy. :-)

**Comment by Shinigami072** [comment]
OK
