### ISSUE TITLE
Black moor colosus zmienił licencję? albo ktoś wstawił bes sprawdzania licencji nie możemy użyć

### ISSUE THREAD

**Issue by Shinigami072** [SuperEpicNothing/str#25]

**Comment by Shinigami072** [comment]
możliwe zamienniki w losowej kolejności:
- http://opengameart.org/content/undead-cyborg
-  http://opengameart.org/content/phase-zero
-  http://opengameart.org/content/battle-march-epic-orchestral-music-loop 
-  http://opengameart.org/content/dark-descent-extended-cut
- http://opengameart.org/content/blackmoor-tides-epic-pirate-battle-theme
- http://opengameart.org/content/defying-commodus
- http://opengameart.org/content/perpetual-tension
- http://opengameart.org/content/its-our-battle
- http://opengameart.org/content/railjet-long-seamless-loop
- http://opengameart.org/content/unused-music
- http://opengameart.org/content/dark-descent
- http://opengameart.org/content/final-epic-battle
- http://opengameart.org/content/heroic-minority
- http://opengameart.org/content/arabesque
- http://opengameart.org/content/music-dark-electronicrocksci-fi-rock-clearside-siste-viator
- http://opengameart.org/content/battle-theme-a
- http://opengameart.org/content/dream-raid-cinematic-action-soundtrack
- http://opengameart.org/content/no-more-magic
- http://opengameart.org/content/heroic-demise-updated-version
- http://opengameart.org/content/the-dark-amulet-dark-mage-theme

**Comment by lukaszlamza** [comment]
Podoba mi się:
http://opengameart.org/content/battle-march-epic-orchestral-music-loop

Ale przyznam, że nie przesłuchałem wszystkich. :)
