### ISSUE TITLE
jest trzeci konfuzjusz

### ISSUE THREAD

**Issue by lukaszlamza** [SuperEpicNothing/str#27]
Elo,

Wrzuciłem wersję roboczą 3ciego Konfuzjusza. Później dorzucę jeszcze więcej opcji konwersacyjnych, ale na razie jest struktura. Miejsca na animacje są następujące:
- animacja argumentu Kartezjusza ("Rzecz myśląca") - scena nr 2;
- animacja argumentu Churchlanda ("Eliminator") - scena nr 3;
- animacja argumentu Jacksona ("Czerwona mgiełka") - scena nr 4;
- animacja argumentu Whiteheada ("Organizm elementarny") - scena nr 7.

Podaję te numery, bo w całej rozmowie jest więcej miejsc, gdzie są mniej istotne testy na obecność tych Argumentów, ale te określone 4 miejsca to są miejsca kluczowe i tam będzie dobre miejsce na animację.

**Comment by Shinigami072** [comment]
ustawiłem animacje
