### ISSUE TITLE
Epilog

### ISSUE THREAD

**Issue by lukaszlamza** [SuperEpicNothing/str#28]
Mam jeszcze prośbę: niech ostatnia walka z Konfuzjuszem odblokowuje dodatkowy plik HTML zatytułowany "Epilog". Może to być ostatnia lekcja (po Konfuzjuszu) w rozdziale Człowiek. Mam poczucie, że grę trzeba jakoś zamknąć.

**Comment by Shinigami072** [comment]
zrobiłem to w taki sposób, epilog jest jak każda inna lekcja, ale jego istnienie jest ukryte do czasu jego odblokowania, nawet przed trybem nauczyciela
