### ISSUE TITLE
No dobra, trochę poszalałem

### ISSUE THREAD

**Issue by lukaszlamza** [SuperEpicNothing/str#30]
Dodałem logo gry na stronie głównej. Nie zabijaj.

Nazwę "Nauka i Wiara" wywalamy z wszystkich miejsc. Cała seria będzie na 95% nosiła nazwę "Filozuj", natomiast podtytuł "Klątwa Konfuzjusza" to był mój szybki pomysł sprzed kwadransa, więc jest pod dyskusję.

**Comment by Shinigami072** [comment]
zrobiłem nowe logo

**Comment by lukaszlamza** [comment]
Jest fajne, ale bardziej podoba mi się moje. :)) Korzystam więc z przywileju starszeństwa i przywracam. Jeżeli chcesz, możemy też poprosić naszych Beta Testerów o opinię - no problem. Jestem jak zwykle otwarty na wszelkie propozycje.

**Comment by lukaszlamza** [comment]
Co do natomiast samej nazwy, "Powrót filozofów" możemy nazwać sequel. Przecież będzie sequel. :D
