### ISSUE TITLE
bug: zablokowuje mi lekcję "Wiedza bezpośrednia"

### ISSUE THREAD

**Issue by lukaszlamza** [SuperEpicNothing/str#33]
Dziwna sprawa... Tuż po rozmowie z Kartezjuszem (rozdział 1, lekcja 1 "Złośliwy demon", czyli plik 0/1.html) poprawnie odblokowuje mi następną lekcję, czyli "Wiedzę bezpośrednią" (plik 0/2.html). Ale jak tylko wywołam tę lekcję, robi się w menu szara i "zablokowana". Potem odblokowuję sobie kolejne lekcje i wszystko jest OK z pozostałymi, ale ta jedna jest cały czas zablokowana. Można ją odblokować tylko w ten sposób, że ponownie przejdzie się przez rozmowę z Kartezjuszem (kartezjusz.json), gdzie w dialogu nr 30 jest komenda odblokowania rozdziału  {"type":"unlockChap","time":"0","chapter":0,"lesson":2}, i wtedy można wejść w lekcję, ale potem znowu się ona zablokowuje. I tylko ta jedna, pozostałe są ok.

**Comment by Shinigami072** [comment]
możliwe że naprawiłem
