### ISSUE TITLE
bug: problemy z konfuzjuszem (isWin)

### ISSUE THREAD

**Issue by lukaszlamza** [SuperEpicNothing/str#34]
isWin przestało działać. Wiesza mi się na pierwszym spotkaniu z Konfuzjuszem w momencie, gdy Konfuzjusz robi isWin (dialog nr 24). Wcześniej już działało.

**Comment by lukaszlamza** [comment]
Natomiast poprawnie odblokowuje nowy rozdział. Więc jedyne, czego nie robi, to nie wyświetla tekstu sceny nr  25.

**Comment by lukaszlamza** [comment]
Momencik, czy teraz właściwie w pliku Konfuzjusza powinno być ręcznie dodane unlockChap czy też zajmuje się tym funkcja isWin i związane? Bo w konfuzjusz1.json jest jeszcze unlockChap, a w konfuzjusz2.json już nic takiego nie ma...

**Comment by Shinigami072** [comment]
potrzebny jest unlock chap, is win jedynie wybiera który event odtworzyć i dodawaniem XP
